dist: metadata-frontend

env:
  global:
    - REGISTRY_NAME=1049651653
    - REGISTRY_PWD=lmg7831336
    - REGISTRY=docker.io/1049651653
    - IMAGE_NAME=metadata-frontend:v0.1.8
    - CODE_TAG=v0.1-branch
    
arch:
#  - amd64
  - arm64

services:
  - docker

before_install:
  - git clone -b ${CODE_TAG} --depth 1 https://github.com/kubeflow/metadata.git

script:
  - cd metadata/frontend
  - docker build -t ${REGISTRY}/${IMAGE_NAME} -f Dockerfile .
  
after_success:
- docker login -u ${REGISTRY_NAME} -p ${REGISTRY_PWD} ${REGISTRY}
- docker push ${REGISTRY}/${IMAGE_NAME}
